requirejs.config({
    baseUrl:'../scripts/lib',
    paths:{
        'app':'../app',
        'client':'../app/client',
        'views':'../app/client/views',
        'mock':'../app/client/mock'
    },
    waitSeconds:10
});
require(['client/bootstrapper'],function(bs){
    bs.run();
});
